# Generated by Django 5.1.7 on 2025-04-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='story',
            field=models.TextField(blank=True, help_text='The story behind the recipe', null=True),
        ),
    ]
