# Generated by Django 5.1.7 on 2025-04-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.CharField(max_length=20),
        ),
    ]
